# Generated by Django 4.0.2 on 2022-02-07 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '디잔고 사용자', 'verbose_name_plural': '디잔고 사용자'},
        ),
    ]
